sync it

diff --git a/docbook-utils/docbook-utils-2ndspaces.patch b/docbook-utils/docbook-utils-2ndspaces.patch
--- a/docbook-utils/docbook-utils-2ndspaces.patch
+++ b/docbook-utils/docbook-utils-2ndspaces.patch
@@ -190,6 +190,15 @@
  fi
 --- Original/bin/jw.in	2003-04-30 18:21:49.000000000 +0200
 +++ Changes/bin/jw.in	2007-05-21 14:28:58.000000000 +0200
+@@ -246,7 +246,7 @@ then
+   echo -e $SGML_HELP_MESSAGE >&2
+   exit 1
+ fi
+-if [ ! -s $SGML_FRONTEND ]
++if [ ! -s "$SGML_FRONTEND" ]
+ then
+   echo "`basename $0`: There is no frontend called \"$SGML_FRONTEND\"." >&2
+   exit 2
 @@ -270,14 +270,14 @@
    echo -e $SGML_HELP_MESSAGE >&2
    exit 1
@@ -225,3 +234,27 @@
  fi
  SGML_RETURN=$?
  cd "$SGML_CURRENT_DIRECTORY"
+diff -urNp docbook-utils-0.6.14-orig/backends/man.in docbook-utils-0.6.14/backends/man.in
+--- docbook-utils-0.6.14-orig/backends/man.in	2003-02-11 13:56:23.000000000 +0100
++++ docbook-utils-0.6.14/backends/man.in	2009-07-24 15:07:04.000000000 +0200
+@@ -7,7 +7,7 @@ HELPER=$SGML_BASE_DIR/docbook/utils-@VER
+ TMPDIR=`mktemp -d /tmp/man.XXXXXX` || \
+  { echo >&2 "man backend: could not create secure temporary directory"; exit 1;}
+ trap 'rm -rf "${TMPDIR}"' EXIT
+-nsgmls $SGML_FILE > "${TMPDIR}/nsgmls.tmp"
++nsgmls "$SGML_FILE" > "${TMPDIR}/nsgmls.tmp"
+ sgmlspl $HELPER <"${TMPDIR}/nsgmls.tmp" 2>"${TMPDIR}/errs"
+ if [ $? -ne 0 ]
+ then
+diff -urNp docbook-utils-0.6.14-orig/backends/texi.in docbook-utils-0.6.14/backends/texi.in
+--- docbook-utils-0.6.14-orig/backends/texi.in	2002-08-05 23:20:56.000000000 +0200
++++ docbook-utils-0.6.14/backends/texi.in	2009-07-24 15:08:02.000000000 +0200
+@@ -3,7 +3,7 @@
+ # This program is under GPL license. See LICENSE file for details.
+ 
+ # Convert to texinfo
+-nsgmls $SGML_FILE | sgmlspl $SGML_BASE_DIR/docbook/utils-@VERSION@/helpers/docbook2texi-spec.pl >$SGML_FILE_NAME.texi
++nsgmls "$SGML_FILE" | sgmlspl $SGML_BASE_DIR/docbook/utils-@VERSION@/helpers/docbook2texi-spec.pl >$SGML_FILE_NAME.texi
+ if [ $? -ne 0 ]
+ then exit 1
+ fi
